#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=15

CONFIG_FILE="/etc/mihomo/tproxy-manager.yaml"
BIN="/usr/bin/mihomo"

start_service() {
  [ -x "$BIN" ] || return 1
  [ -f "$CONFIG_FILE" ] || return 1
  config_dir="${CONFIG_FILE%/*}"
  procd_open_instance
  procd_set_param command "$BIN" -d "$config_dir" -f "$CONFIG_FILE"
  procd_set_param env SAFE_PATHS="$config_dir"
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_set_param respawn 3600 5 5
  procd_close_instance
}

reload_service() {
  restart
}
