#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=15

CONFIG_FILE="/etc/sing-box/tproxy-manager.json"
BIN="/usr/bin/sing-box"

start_service() {
  [ -x "$BIN" ] || return 1
  [ -f "$CONFIG_FILE" ] || return 1
  procd_open_instance
  procd_set_param command "$BIN" run -c "$CONFIG_FILE"
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_set_param respawn 3600 5 5
  procd_close_instance
}

reload_service() {
  restart
}
