#!/bin/sh /etc/rc.common

USE_PROCD=1
START=96
STOP=20

SERVICE_BIN="/usr/bin/tproxy-manager-watchdog.sh"

start_service() {
    [ -x "$SERVICE_BIN" ] || return 1
    procd_open_instance
    procd_set_param command "$SERVICE_BIN" run
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

reload_service() {
    stop
    start
}

service_triggers() {
    procd_add_reload_trigger "tproxy-manager"
}
