name: Build .ipk via official ipkg-build (OpenWrt 24.10)

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
    paths:
      - "pkg/**"
      - ".github/workflows/build-ipk.yml"
  workflow_dispatch: {}

permissions:
  contents: write

env:
  PKG_DIR: pkg/tproxy-manager-ipk

jobs:
  build-ipk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute version
        id: ver
        shell: bash
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            VER="${GITHUB_REF_NAME}"
          else
            VER="$(date -u +%Y.%m.%d)-${GITHUB_SHA::7}"
          fi
          echo "version=$VER" >> "$GITHUB_OUTPUT"

      - name: Install base tools
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            ca-certificates curl xz-utils gzip tar coreutils findutils gawk sed

      - name: Fetch ipkg-build (OpenWrt 24.10)
        run: |
          curl -fsSL https://raw.githubusercontent.com/openwrt/openwrt/openwrt-24.10/scripts/ipkg-build -o ipkg-build
          chmod +x ipkg-build
          ./ipkg-build -h || true

      - name: Sanity & perms
        run: |
          CTRL="$PKG_DIR/CONTROL/control"
          [[ -f "$CTRL" ]] || { echo "Missing $CTRL"; exit 1; }
          sed -i 's/\r$//' "$CTRL" || true
          perl -0777 -pe 's/^\xEF\xBB\xBF//' -i "$CTRL" || true
          find "$PKG_DIR" -type f -path '*/etc/init.d/*' -exec chmod 0755 {} +
          find "$PKG_DIR" -type f -path '*/etc/uci-defaults/*' -exec chmod 0755 {} +
          [ -f "$PKG_DIR/CONTROL/postinst" ] && chmod 0755 "$PKG_DIR/CONTROL/postinst" || true
          [ -f "$PKG_DIR/CONTROL/prerm" ]    && chmod 0755 "$PKG_DIR/CONTROL/prerm"    || true
          [ -f "$PKG_DIR/usr/bin/xray-tproxy.sh" ] && chmod 0755 "$PKG_DIR/usr/bin/xray-tproxy.sh" || true

      - name: Inject Version into control
        run: |
          CTRL="$PKG_DIR/CONTROL/control"
          if grep -q '^Version:' "$CTRL"; then
            sed -i "s/^Version:.*/Version: ${{ steps.ver.outputs.version }}-1/" "$CTRL"
          else
            echo "Version: ${{ steps.ver.outputs.version }}-1" >> "$CTRL"
          fi

      - name: Build .ipk via ipkg-build (ABS dest)
        shell: bash
        run: |
          DEST="$(pwd)/dist"
          mkdir -p "$DEST"
          ./ipkg-build "$PKG_DIR" "$DEST"
          ls -lah "$DEST"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ipk
          path: dist/*.ipk