name: Build OpenWrt .ipk (TPROXY-Manager) + Feed + Pages

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"
    paths:
      - "pkg/**"
      - "keys/**"
      - ".github/workflows/build-ipk.yml"
      - "README.md"
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

env:
  PKG_DIR: pkg/tproxy-manager-ipk
  FEED_DIR: feed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Compute version
        id: ver
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            VER="${GITHUB_REF_NAME}"
          else
            VER="$(date -u +%Y.%m.%d)-${GITHUB_SHA::7}"
          fi
          echo "version=$VER" >> $GITHUB_OUTPUT

      - name: Install base build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake xz-utils tar coreutils gzip

      # ✅ ПОДТЯГИВАЕМ opkg-utils через actions/checkout (а не git clone)
      - name: Fetch opkg-utils source
        uses: actions/checkout@v4
        with:
          repository: openwrt/opkg-utils
          path: opkg-utils
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install opkg-utils
        run: |
          sudo make -C opkg-utils install PREFIX=/usr/local
          command -v opkg-build && opkg-build --help | head -n 1

      # ✅ ПОДТЯГИВАЕМ usign через actions/checkout (а не git clone)
      - name: Fetch usign source
        uses: actions/checkout@v4
        with:
          repository: openwrt/usign
          path: usign
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & install usign
        run: |
          mkdir -p usign/build
          cd usign/build
          cmake ..
          make -j$(nproc)
          sudo make install
          command -v usign && usign -h | head -n 1

      - name: Set permissions (safety)
        run: |
          find "$PKG_DIR" -type f -path '*/etc/init.d/*' -exec chmod 0755 {} +
          find "$PKG_DIR" -type f -path '*/etc/uci-defaults/*' -exec chmod 0755 {} +
          if [ -f "$PKG_DIR/CONTROL/postinst" ]; then chmod 0755 "$PKG_DIR/CONTROL/postinst"; fi
          if [ -f "$PKG_DIR/CONTROL/prerm" ];   then chmod 0755 "$PKG_DIR/CONTROL/prerm";   fi
          if [ -f "$PKG_DIR/usr/bin/xray-tproxy.sh" ]; then chmod 0755 "$PKG_DIR/usr/bin/xray-tproxy.sh"; fi

      - name: Inject version into control
        run: |
          CTRL="$PKG_DIR/CONTROL/control"
          if grep -q '^Version:' "$CTRL"; then
            sed -i "s/^Version:.*/Version: ${{ steps.ver.outputs.version }}-1/" "$CTRL"
          else
            echo "Version: ${{ steps.ver.outputs.version }}-1" >> "$CTRL"
          fi

      - name: Build .ipk
        run: |
          mkdir -p dist
          opkg-build -Z xz -o 0 -g 0 "$PKG_DIR" dist
          ls -lah dist

      - name: Prepare feed
        run: |
          rm -rf "$FEED_DIR"
          mkdir -p "$FEED_DIR/keys"
          cp dist/*.ipk "$FEED_DIR"/
          (cd "$FEED_DIR" && opkg-make-index . > Packages)
          gzip -kf "$FEED_DIR/Packages"
          if ls keys/*.pub >/dev/null 2>&1; then
            cp keys/*.pub "$FEED_DIR/keys/"
          elif [ -f keys/usign.pub ]; then
            cp keys/usign.pub "$FEED_DIR/keys/"
          fi
          cat > "$FEED_DIR/README_FEED.txt" <<'EOF'
          This is an OpenWrt package feed for TPROXY-Manager.
          Files:
            - Packages / Packages.gz / Packages.sig
            - *.ipk
            - keys/ (public usign keys)
          EOF

      - name: Check if signing secret present
        id: has_secret
        shell: bash
        run: |
          if [ -n "${{ secrets.USIGN_SECRET }}" ]; then
            echo "present=1" >> "$GITHUB_OUTPUT"
          else
            echo "present=0" >> "$GITHUB_OUTPUT"
          fi

      - name: Sign feed (optional)
        if: ${{ steps.has_secret.outputs.present == '1' }}
        env:
          USIGN_SECRET: ${{ secrets.USIGN_SECRET }}
        run: |
          echo "$USIGN_SECRET" | base64 -d > /tmp/usign.key
          chmod 600 /tmp/usign.key
          usign -S -m "$FEED_DIR/Packages" -s /tmp/usign.key

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ipk-and-feed
          path: |
            dist/*.ipk
            feed/*

  deploy-pages:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'tag' || github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ipk-and-feed
          path: public
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4